uebung7/Vorlesung7_PyCharm_project/Books/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('show/', views.BookListView.as_view(), name='book-list'),
    #path('show/', views.book_list, name='book-list'),
    #path('show/<int:pk>/', views.BookDetailView.as_view(), name='book-detail'),
    path('show/<int:pk>/', views.book_detail, name='book-detail'),
    path('show/<int:pk>/vote/<str:up_or_down>/', views.vote, name='book-vote'),
    path('add/', views.BookCreateView.as_view(), name='book-create'),
]

uebung7/Vorlesung7_PyCharm_project/Computers/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('show/', views.computer_list, name='computer-list'),
    path('show/<int:pk>/', views.computer_detail, name='computer-detail'),
    path('add/', views.computer_create, name='computer-create'),
]

uebung7/Vorlesung7_PyCharm_project/Vorlesung7/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', TemplateView.as_view(template_name='home.html'), name='home'),
    path('useradmin/', include('Useradmin.urls')),
    path('useradmin/', include('django.contrib.auth.urls')),
    path('books/', include('Books.urls')),
    path('computers/', include('Computers.urls')),
]

uebung7/Vorlesung7_PyCharm_project/Computers/models.py
from django.db import models
from django.contrib.auth.models import User


class Computer(models.Model):
    BRANDS = [
        ('A', 'Apple'),
        ('H', 'HP'),
        ('M', 'Microsoft'),
        ('S', 'Sony'),
    ]

    TYPES = [
        ('D', 'Desktop'),
        ('L', 'Laptop'),
        ('N', 'Netbook'),
    ]

    OPERATING_SYSTEMS = [
        ('L', 'Linux'),
        ('M', 'MacOS'),
        ('W', 'Windows'),
    ]

    brand = models.CharField(max_length=1,
                            choices=BRANDS,
                            )
    type = models.CharField(max_length=1,
                            choices=TYPES,
                            )
    operating_system = models.CharField(max_length=1,
                            choices=OPERATING_SYSTEMS,
                            )
    memory = models.IntegerField()  # Must call function to take effect
    serial_number = models.CharField(max_length=50)
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             related_name='computer_created_by',
                             related_query_name='computer_created_by',
                             )

    class Meta:
        ordering = ['type', 'brand', 'serial_number']
        verbose_name = 'Computer'
        verbose_name_plural = 'Computers'

    def __str__(self):
        return self.get_brand_display() + ' / ' + self.get_type_display()

    def __repr__(self):
        return self.get_brand_display() + ' / ' + self.get_type_display() + ' / ' + self.get_operating_system_display() + ' / ' + str(self.memory) + ' Gb'

uebung7/Vorlesung7_PyCharm_project/Computers/forms.py
from django import forms
from .models import Computer


class ComputerForm(forms.ModelForm):

    class Meta:
        model = Computer
        fields = ['brand', 'type', 'operating_system', 'memory', 'serial_number']
        widgets = {
            'brand': forms.Select(choices=Computer.BRANDS),
            'type': forms.Select(choices=Computer.TYPES),
            'operating_system': forms.Select(choices=Computer.OPERATING_SYSTEMS),
            'user': forms.HiddenInput(),
        }

uebung7/Vorlesung7_PyCharm_project/Computers/views.py
from django.shortcuts import redirect, render
from .forms import ComputerForm
from .models import Computer


def computer_list(request):
    all_the_computers_in_my_function_based_view = Computer.objects.all()
    # print('I am in computer_list')
    # print(all_the_computers_in_my_function_based_view)
    context = {'all_the_computers': all_the_computers_in_my_function_based_view}
    return render(request, 'computer-list.html', context)


def computer_detail(request, **kwargs):
    # print(kwargs)
    computer_id = kwargs['pk']
    that_one_computer_in_my_function_based_view = Computer.objects.get(id=computer_id)
    # print(str(computer_id), " :: ", that_one_computer_in_my_function_based_view)
    context = {'that_one_computer': that_one_computer_in_my_function_based_view}
    return render(request, 'computer-detail.html', context)


def computer_create(request):
    if request.method == 'POST':
        # print("I am in POST")
        form_in_my_function_based_view = ComputerForm(request.POST)
        form_in_my_function_based_view.instance.user = request.user
        if form_in_my_function_based_view.is_valid():
            form_in_my_function_based_view.save()
            # print("I saved new computer")
        else:
            pass
            # print(form_in_my_function_based_view.errors)

        return redirect('computer-list')

    else:  # request.method == 'GET'
        # print("I am in GET")
        form_in_my_function_based_view = ComputerForm()
        context = {'form': form_in_my_function_based_view}
        return render(request, 'computer-create.html', context)

uebung7/Vorlesung7_PyCharm_project/Computers/templates/computer-create.html
{% extends 'home.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'Computers/computers_style.css' %}">
{% endblock %}

{% block title %}Add computer{% endblock %}

{% block logged_in_content %}
<h2>Add computer</h2>
    <form method="POST">
        {% csrf_token %}

        <label for="id_brand">Brand:</label>
        <select id="id_brand" type="text" name="brand">
            <option value="A">Apple</option>
            <option value="H">HP</option>
            <option value="M">Microsoft</option>
            <option value="S">Sony</option>
        </select>
        <br><br>

        {{ form.type.label }}: {{ form.type }}<br><br>

        {{ form.operating_system.label }}: {{ form.operating_system }}<br><br>

        <label for="{{ form.memory.id_for_label }}">{{ form.memory.label }}:</label>
        <input id="{{ form.memory.id_for_label }}" type="{{ form.memory.field.widget.input_type }}" name="{{ form.memory.html_name }}"> Gb<br><br>

        {{ form.serial_number.label }}:
        {{ form.serial_number }}<br><br>

        <!-- {{ form.as_p }} -->

        <button type="submit">Add computer</button>
    </form>
{% endblock %}

uebung7/Vorlesung7_PyCharm_project/Computers/templates/computer-detail.html
{% extends 'home.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'Computers/computers_style.css' %}">
{% endblock %}

{% block title %}Computer detail{% endblock %}

{% block content %}
<h2>Computer detail</h2>

    <table>
    <tr>
        <td><b>Brand:</b></td>
        <td>{{ that_one_computer.get_brand_display }}<br></td>
    </tr>
    <tr>
        <td><b>Type:</b></td>
        <td>{{ that_one_computer.get_type_display }}<br></td>
    </tr>
    <tr>
        <td><b>Operating system:</b></td>
        <td>{{ that_one_computer.get_operating_system_display }}<br></td>
    </tr>
    <tr>
        <td><b>Memory:</b></td>
        <td>{{ that_one_computer.memory }}<br></td>
    </tr>
    <tr>
        <td><b>Serial number:</b></td>
        <td>{{ that_one_computer.serial_number }}<br></td>
    </tr>
    <tr>
        <td><b>Entered by:</b></td>
        <td>{{ that_one_computer.user }}<br></td>
    </tr>
    </table>

    <br>
    <a href="{% url 'computer-list' %}">Back to all computers</a>
{% endblock %}

uebung7/Vorlesung7_PyCharm_project/Computers/templates/computer-list.html
{% extends 'home.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'Computers/computers_style.css' %}">
{% endblock %}

{% block title %}Computers list{% endblock %}

{% block content %}
<h2>Computers list</h2>
<ul>
    {% for computer in all_the_computers %}
        <a href="{{ computer.id }}/"><b>{{ computer.get_brand_display }}</b> {{ computer.serial_number }}</a><br>
        <!-- Alternative link:
        <a href="{% url 'computer-detail' computer.id %}">
        -->
        {{ computer.get_type_display }} / {{ computer.get_operating_system_display }} / {{ computer.memory }} Gb<br>
        <br>
    {% endfor %}
</ul>

<a href="{% url 'computer-create' %}">Add a new computer</a><br>
{% endblock %}