uebung7/Uebung7_PyCharm_project_cloned-u5/ComputerGame/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('show/', views.computer_games_list, name='games-list'),
    path('show/<int:pk>/', views.computer_game_details, name='game-detail'),
    path('add/', views.create_computer_game, name='game-create'),
    path('<pk>/delete/', views.delete_game, name='game-confirm-delete'),
    path('show/<int:pk>/vote/<str:up_or_down>/comment/<int:commentPK>', views.vote, name='game-vote'),

]

uebung7/Uebung7_PyCharm_project_cloned-u5/Useradmin/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup')
]

uebung7/Uebung7_PyCharm_project_cloned-u5/uebung5/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', TemplateView.as_view(template_name='home.html'), name='home'),
    path('games/', include('ComputerGame.urls')),
    path('useradmin/', include('Useradmin.urls')),
    path('useradmin/', include('django.contrib.auth.urls'))
]

uebung7/Uebung7_PyCharm_project_cloned-u5/ComputerGame/models.py
from datetime import date
from django.db import models
from django.contrib.auth.models import User


class ComputerGame(models.Model):
    name = models.CharField(max_length=50)
    GAMES_TYPES = [('FPS', 'First person shot'), ('PUZ', 'Puzzle'), ('STR', 'Strategy')]
    description = models.CharField(max_length=100,
                                   blank=True)
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             related_name='users',
                             related_query_name='user',
                             )

    added_on = models.DateField(blank=True,
                                default=date.today,
                                )
    genre = models.CharField(max_length=3,
                             choices=GAMES_TYPES,
                             )

    class Meta:
        ordering = ['name']
        verbose_name = 'ComputerGame'
        verbose_name_plural = 'ComputerGame'

    def get_upvotes(self):
        upvotes = Vote.objects.filter(up_or_down='up',
                                      game=self)
        return upvotes

    def get_upvotes_count(self):
        return len(self.get_upvotes())

    def get_downvotes(self):
        downvotes = Vote.objects.filter(up_or_down='down',
                                        game=self)
        return downvotes

    def get_downvotes_count(self):
        return len(self.get_downvotes())

    def vote(self, user, up_or_down, comment):
        prev_vote = Vote.objects.filter(user=user, comment=comment)
        if len(prev_vote) == 0:
            Vote.objects.create(up_or_down=up_or_down,
                                user=user,
                                game=self,
                                comment=comment
                                )
        else:
            prev_vote.update(up_or_down=up_or_down)


class Comment(models.Model):
    text = models.TextField(max_length=500)
    timestamp = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    game = models.ForeignKey(ComputerGame, on_delete=models.CASCADE)

    class Meta:
        ordering = ['timestamp']
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'

    def get_comment_prefix(self):
        if len(self.text) > 50:
            return self.text[:50] + '...'
        else:
            return self.text

    def __str__(self):
        return self.get_comment_prefix() + ' (' + self.user.username + ')'

    def __repr__(self):
        return self.get_comment_prefix() + ' (' + self.user.username + ' / ' + str(self.timestamp) + ')'


class Vote(models.Model):
    VOTE_TYPES = [
        ('U', 'up'),
        ('D', 'down'),
    ]

    up_or_down = models.CharField(max_length=1,
                                  choices=VOTE_TYPES,
                                  )
    timestamp = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    game = models.ForeignKey(ComputerGame, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)

uebung7/Uebung7_PyCharm_project_cloned-u5/Useradmin/models.py
from django.db import models

# Create your models here.

uebung7/Uebung7_PyCharm_project_cloned-u5/ComputerGame/forms.py
from django import forms
from .models import ComputerGame, Comment


class GameForm(forms.ModelForm):
    class Meta:
        model = ComputerGame
        fields = ['name', 'description', 'genre', 'added_on']
        widgets = {
            'genre': forms.Select(choices=ComputerGame.GAMES_TYPES),
            'user': forms.HiddenInput(),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            'user': forms.HiddenInput(),
            'game': forms.HiddenInput(),
        }

uebung7/Uebung7_PyCharm_project_cloned-u5/ComputerGame/views.py
from django.shortcuts import redirect, render
from .models import ComputerGame, Comment, Vote
from .forms import GameForm, CommentForm


def computer_games_list(request):
    all_games = ComputerGame.objects.all()
    context = {'all_games': all_games}
    return render(request, 'game-list.html', context)


def computer_game_details(request, **kwargs):
    computer_game_id = kwargs['pk']
    selected_game = ComputerGame.objects.get(id=computer_game_id)

    # Add comment
    if request.method == 'POST':
        form = CommentForm(request.POST)
        form.instance.user = request.user
        form.instance.game = selected_game
        if form.is_valid():
            form.save()
        else:
            print(form.errors)
    comments = Comment.objects.filter(game=selected_game)
    comments_votes = Vote.objects.filter(game=selected_game)
    comments_with_votes = []
    for com in comments:
        up_votes = 0
        down_votes = 0
        for comment_vote in comments_votes:
            if comment_vote.up_or_down == "up" and comment_vote.comment_id == com.id:
                up_votes = up_votes + 1
            elif comment_vote.up_or_down == "down" and comment_vote.comment_id == com.id:
                down_votes = down_votes + 1
        comments_with_votes.append({'comment': com, 'up_votes': up_votes, 'down_votes': down_votes})

    context = {'that_game': selected_game,
               'comments_for_that_game': comments,
               'comment_form': CommentForm,
               'comments_with_votes': comments_with_votes}
    return render(request, 'game-detail.html', context)


def create_computer_game(request):
    if request.method == 'POST':
        form_in_my_function_based_view = GameForm(request.POST)
        form_in_my_function_based_view.instance.user = request.user
        if form_in_my_function_based_view.is_valid():
            form_in_my_function_based_view.save()
        else:
            pass
            print(form_in_my_function_based_view.errors)

        return redirect('games-list')

    else:  # request.method == 'GET'
        form_in_my_function_based_view = GameForm()
        print(form_in_my_function_based_view)
        context = {'form': form_in_my_function_based_view}
        return render(request, 'game-create.html', context)


def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)


def delete_game(request, **kwargs):
    computer_game_id = kwargs['pk']
    if request.method == 'POST':
        ComputerGame.objects.filter(id=computer_game_id).delete()
        all_games = ComputerGame.objects.all()
        context = {'all_games': all_games}
        return render(request, 'game-list.html', context)
    else:
        selected_game = ComputerGame.objects.get(id=computer_game_id)
        context = {'game': selected_game}
        return render(request, 'game-confirm-delete.html', context)


def vote(request, pk: str, up_or_down: str, commentPK: int):
    game = ComputerGame.objects.get(id=int(pk))
    user = request.user
    comment = Comment.objects.get(id=commentPK)
    game.vote(user, up_or_down, comment)
    return redirect('game-detail', pk=pk)

uebung7/Uebung7_PyCharm_project_cloned-u5/Useradmin/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


# Useradmin/views.py

# Question:
# we imported -> from django.shortcuts import render , but we didn't use it, do we still need it ?!
class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

uebung7/Uebung7_PyCharm_project_cloned-u5/ComputerGame/templates/game-confirm-delete.html
{% extends 'home.html' %}

{% block title %}delete game{% endblock %}

{% block logged_in_content %}
    <h1 class="header-home">Delete confirmation</h1>
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ game.name }}"?</p>
        <input type="submit" value="Confirm">
    </form>
{% endblock %}

uebung7/Uebung7_PyCharm_project_cloned-u5/ComputerGame/templates/game-create.html
{% extends 'home.html' %}

{% block title %}Add game{% endblock %}

{% block logged_in_content %}
    <h2 class="header-home">Add computer Game</h2>
    <form method="POST">
        {% csrf_token %}

        <label for="id_name">Name:</label>
        <input id="id_name" type="text" name="name"> <br><br>

        <label for="id_description">Description:</label>
        <input id="id_description" type="text" name="description"> <br><br>

        <label for="id_genre">Genre:</label>
        <select id="id_genre" type="text" name="genre">
            {% for item in form.genre %}
                <option {{ item }} {% if item == id_genre %} selected {% endif %}>
            {% endfor %}
        </select>

        <br><br>
        <label for="id_added_on">Added_on:</label>
        <input id="id_added_on" type="date" name="added_on"> <br><br>

        <button type="submit">Add Game</button>
    </form>
{% endblock %}

{% block not_logged_in_content %}
    <p>You must log in to add game</p>
    <a href="{% url 'login' %}">Login</a>
{% endblock %}

uebung7/Uebung7_PyCharm_project_cloned-u5/ComputerGame/templates/game-detail.html
{% extends 'home.html' %}
{% load static %}

{% block title %}Game detail{% endblock %}

{% block content %}
    <h1 class="header-home">Game detail</h1>

    <table>
        <tr>
            <td><b>name:</b></td>
            <td>{{ that_game.name }}<br></td>
        </tr>
        <tr>
            <td><b>description:</b></td>
            <td>{{ that_game.description }}<br></td>
        </tr>
        <tr>
            <td><b>added on:</b></td>
            <td>{{ that_game.added_on }}<br></td>
        </tr>

        <tr>
            <td><b>added by:</b></td>
            <td>{{ that_game.user.username }}<br></td>
        </tr>
    </table>

    {% for comment_with_vote in comments_with_votes %}
        <div style="border: 1px solid black; margin:15px">
            <b style="color: darkgreen">{{ comment_with_vote.comment.user.username }}
                on {{ comment_with_vote.comment.timestamp }}</b><br>
            {{ comment_with_vote.comment.text }}<br><br>
            <span style="color: darkgreen">{{ comment_with_vote.up_votes }}</span>
            <a href="{% url 'game-vote' that_game.id 'up' comment_with_vote.comment.id %}"
               style="text-decoration: none">
                <img src="{% static 'ComputerGame/arrow_up.png' %}" height="20" width="20">
            </a>
            &nbsp;&nbsp;&nbsp;
            <span style="color: crimson">{{ comment_with_vote.down_votes }}</span>
            <a href="{% url 'game-vote' that_game.id 'down' comment_with_vote.comment.id %}"
               style="text-decoration: none">
                <img src="{% static 'ComputerGame/arrow_down.png' %}" height="20" width="20">
            </a>
            <br><br>
        </div>

    {% endfor %}

    <br>




    <b style="color: crimson">Do you have a comment for this game?</b><br>
    <form method="POST">
        {% csrf_token %}
        {{ comment_form.as_p }}
        <button type="submit">Add comment</button>

    </form>


    <a href="{% url 'game-confirm-delete' that_game.id %}">Delete this game</a>
    <br>
    <a href="{% url 'games-list' %}">Back to all games</a>
{% endblock %}

uebung7/Uebung7_PyCharm_project_cloned-u5/ComputerGame/templates/game-list.html
{% extends 'home.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/home_style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'ComputerGame/computerGame_style.css' %}">
{% endblock %}

{% block title %}Games list{% endblock %}

{% block content %}
    <h1 class="header-home">Games list</h1>
    <ul>
        {% for game in all_games %}
            <div class="game-wrapper">
                <a href="{{ game.id }}/"><b>{{ game.name }}</b></a>
                <a href="{% url 'game-detail' game.id %}"> </a>
                {{ game.name }} / {{ game.added_on }}
            </div>


        {% endfor %}
    </ul>


    <a class="add-new-game-link" href={% url 'game-create' %}>Add a new game</a><br>
{% endblock %}

uebung7/Uebung7_PyCharm_project_cloned-u5/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    {% block css %}{% endblock %}
    <title>{% block title %}Base Titel{% endblock %}</title>
</head>
<body>
    {% block content %}Base Block{% endblock %}
</body>
</html>

uebung7/Uebung7_PyCharm_project_cloned-u5/templates/home.html
{% extends "base.html" %}

{% load static %}
{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/home_style.css' %}">
{% endblock %}

{% block title %}Home{% endblock %}
{% block content %}

    {% if user.is_authenticated %}
        {% block logged_in_content %}
            <h1 class="header-home">Home</h1>
            <p>Hi {{ user.username }}!</p>
            <p><a href="{% url 'games-list' %}">Show me the games</a></p>
            <a href="{% url 'logout' %}">logout</a>
        {% endblock %}
    {% else %}
        {% block not_logged_in_content %}
            <h1 class="header-home">Home</h1>
            <p>You are not logged in</p>
            <a href="{% url 'login' %}">login</a>
        {% endblock %}
    {% endif %}
{% endblock %}

uebung7/Uebung7_PyCharm_project_cloned-u5/templates/signup.html
{% extends 'base.html' %}
{% block title %}Sign Up{% endblock %}
{% block content %}
    <h2>Sign up</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Sign up</button>
    </form>
{% endblock %}